services:
    # --- Microservicio de YOLO ---
#    yolo:
#        build: ./servicio_yolo
#        container_name: yolo_container
#        ports:
#        - "8001:8001"
#        restart: unless-stopped

    # --- Microservicio de YOLOE ---
    yoloe:
        build: ./servicio_yoloe
        container_name: yoloe_container
        ports:
        - "8001:8001"
        restart: unless-stopped

    # --- Microservicio de MiDaS ---
    midas:
        build: ./servicio_midas
        container_name: midas_container
        ports:
        - "8002:8002"
        restart: unless-stopped

    # --- Microservicio del LLM (Llama.cpp) ---
    llm:
        image: ghcr.io/ggml-org/llama.cpp:server
        container_name: llm_container
        ports:
        - "8080:8080"
        volumes:
        - ./modelos:/models
        # Comando para arrancar el servidor de llama.cpp apuntando a tu GGUF
        command: "-m /models/Qwen3.5-2B-Q4_K_M.gguf --host 0.0.0.0 --port 8080 -c 2048  --chat-template-kwargs '{\"enable_thinking\":false}'"
        restart: unless-stopped

    # --- Microservicio del Backend ---
    backend:
        build: ./servicio_backend
        container_name: backend_container
        ports:
        - "8000:8000"
        restart: unless-stopped
        environment:
        - URL_YOLO=http://yolo:8001/detect
        - URL_MIDAS=http://midas:8002/depth
        - URL_LLM=http://llm:8080/v1/chat/completions
        depends_on:
#        - yolo
        - yoloe
        - midas
        - llm
